services:
  flask:
    build: .
    container_name: flask-ai-server
    ports:
      - "5050:5050"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/health"]
      interval: 30s
      timeout: 10s
      retries: 3