name: Deploy to EC2 via SSM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Send command to EC2
        uses: aws-actions/aws-ssm-send-command@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          instance-ids: ${{ secrets.EC2_INSTANCE_ID }}
          document-name: AWS-RunShellScript
          comment: "Deploying latest image"
          parameters: commands=["cd ~/your-folder && git pull && docker compose up -d"]